### ISSUE TITLE
Buttons not popping up

### ISSUE THREAD

**Issue by Brolafd** [Jurassic001/Auto-Bean#12]
I'm using opera GX and the bot is working but the buttons are not popping up.

**Comment by Jurassic001** [comment]
I've just attempted to reproduce your problem on Opera GX and when I scrolled down to the bottom the buttons were appearing, can you let me know anything else about the conditions surrounding the issue?

**Comment by Brolafd** [comment]
I fixed it, I had tried to modify the code to allow variable accuracy but I messed up and got rid the buttons by accident
