### ISSUE TITLE
Gets stuck on restudy

### ISSUE THREAD

**Issue by LouisDrae** [Jurassic001/Auto-Bean#2]
When purposely skipping a question to lower accuracy, the membean bot will throw an error and will stop. 

`Uncaught TypeError: Cannot read properties of undefined (reading 'click')
    at press (<anonymous>:104:16)
press @ VM172:104`

Everything else works perfectly, it's just this one error that completely stops the membean bot.

**Comment by Jurassic001** [comment]
Ok it seems like the bot failed to detect the restudy page, most likely due to a timing issue. v4.50 should fix this as the timing system has been redesigned to allow for a little bit of wiggle room in-between pages. Let me know if issues like these keep occurring and I'll try to patch them ASAP
