### ISSUE TITLE
Make it so we can set custom accuracies 

### ISSUE THREAD

**Issue by MysticsV2** [Jurassic001/Auto-Bean#23]
I usually like sitting somewhere between 70-75% and wanted to know if I can do something to do so

**Comment by MysticsV2** [comment]
> I don't plan on adding custom accuracies to the script itself, just because changing accuracy mid-session would require either adding a lot of buttons to the page or requiring the user to change the accuracy range through a function in the console (not very user friendly). If you want to change the accuracy for yourself though, I'd recommend forking this repository and changing the accuracy calculation to look like this: 
> 
> ```
> 
> while (targ_accu == 0){
> 
> 	accu_reduction = (Math.random() * 5);
> 
> 	targ_accu = 75 - accu_reduction;
> 
> 	disp_accu = targ_accu.toFixed(0);
> 
> 	targ_accu = targ_accu / 100;
> 
> 	console.log("Session Accuracy Target is " + disp_accu + "%");
> 
> }
> 
> ```
> 
> The above code would pick a random accuracy target between 70 and 75%. If you don't want to bother with forking the repo or you want to stay up to date with future updates, I would just type `targ_accu = 0.74` into the console every time you start the script, and that should give you the same result.
> 
> 
> 
> Let me know if you have any questions.

Do I like paste the script, hit enter, and then type like targ_accu = 0.74? Will it change the accuracy it set automatically?

**Comment by Jurassic001** [comment]
> > I don't plan on adding custom accuracies to the script itself, just because changing accuracy mid-session would require either adding a lot of buttons to the page or requiring the user to change the accuracy range through a function in the console (not very user friendly). If you want to change the accuracy for yourself though, I'd recommend forking this repository and changing the accuracy calculation to look like this:
> > ```
> > 
> > while (targ_accu == 0){
> > 
> > 	accu_reduction = (Math.random() * 5);
> > 
> > 	targ_accu = 75 - accu_reduction;
> > 
> > 	disp_accu = targ_accu.toFixed(0);
> > 
> > 	targ_accu = targ_accu / 100;
> > 
> > 	console.log("Session Accuracy Target is " + disp_accu + "%");
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The above code would pick a random accuracy target between 70 and 75%. If you don't want to bother with forking the repo or you want to stay up to date with future updates, I would just type `targ_accu = 0.74` into the console every time you start the script, and that should give you the same result.
> > Let me know if you have any questions.
> 
> Do I like paste the script, hit enter, and then type like targ_accu = 0.74? Will it change the accuracy it set automatically?

Yeah you would just activate the script normally and then type the command in. It'll override the accuracy that it set when the script started and it'll target the new accuracy instead.

**Comment by MysticsV2** [comment]
Can I close the console after I start the script or do I need to keep it open

**Comment by Jurassic001** [comment]
> Can I close the console after I start the script or do I need to keep it open

Sorry for the late reply, but yes you can close the console. I've personally never had an issue with closing the console but if you do let me know.
