### ISSUE TITLE
Use in Extension

### ISSUE THREAD

**Issue by RedYetiDev** [Jurassic001/Auto-Bean#25]
Dear @Jurassic001,

I've been working on an extension that aligns with the same objectives as your code. I'm interested in incorporating your code as the backend for my extension. Your contribution will be credited.

May I have your permission to proceed with my project?

To clarify, I won't be using an exact copy of your code, but I'm inspired by the way your code works, and I wouldn't want to rip that off.

Thank you,
@RedYetiDev

**Comment by Jurassic001** [comment]
That sounds super interesting, feel free to use my code! Also, Let me know if you have any questions about the inner workings of Membean.

Can't wait to see the finished product!

**Comment by RedYetiDev** [comment]
Thank you!
