### ISSUE TITLE
bot gets stuck sometimes when definition shows up

### ISSUE THREAD

**Issue by shttyktty** [Jurassic001/Auto-Bean#3]
ive noticed that when a word is skipped, and takes you to the definition, it will get stuck and stop answering questions. Ive only seen it click the next button once.

**Comment by Jurassic001** [comment]
Fixed this issue about a week ago, I failed to realize that if the bot waits longer than the allotted time that the allotted time data wouldn't exist by the time its done waiting. Should be all good now, let me know if something else comes up.
